/**
 * 权限领域 - 枚举定义
 */

/**
 * 能力枚举
 * 定义用户可执行的操作能力
 */
export enum Capability {
  VIEW_MALL = 'VIEW_MALL',
  NAVIGATE = 'NAVIGATE',
  EDIT_MALL_STRUCTURE = 'EDIT_MALL_STRUCTURE',
  EDIT_OWN_STORE = 'EDIT_OWN_STORE',
  MANAGE_MERCHANTS = 'MANAGE_MERCHANTS',
  APPLY_MODELING_PERMISSION = 'APPLY_MODELING_PERMISSION',
  APPROVE_MODELING_PERMISSION = 'APPROVE_MODELING_PERMISSION',
  REVOKE_MODELING_PERMISSION = 'REVOKE_MODELING_PERMISSION',
  EDIT_AUTHORIZED_AREA = 'EDIT_AUTHORIZED_AREA',
  SUBMIT_LAYOUT_PROPOSAL = 'SUBMIT_LAYOUT_PROPOSAL',
  REVIEW_LAYOUT_PROPOSAL = 'REVIEW_LAYOUT_PROPOSAL',
  PUBLISH_LAYOUT_VERSION = 'PUBLISH_LAYOUT_VERSION',
  VIEW_LAYOUT_HISTORY = 'VIEW_LAYOUT_HISTORY'
}
